[colors.primary]
background = "#20202a"
foreground = "#abb2bf"

[colors.cursor]
text = "#20202a"
cursor = "#dedede"

[colors.selection]
text = "#abb2bf"
background = "#40375e"

[colors.normal]
black = "#20202a"
red = "#fb7385"
green = "#98c379"
yellow = "#e5bc66"
blue = "#61afef"
magenta = "#ce95b8"
cyan = "#56b6c2"
white = "#abb2bf"

[colors.bright]
black = "#495162"
red = "#fb7385"
green = "#98c379"
yellow = "#e5bc66"
blue = "#61afef"
magenta = "#ce95b8"
cyan = "#56b6c2"
white = "#abb2bf"
