[colors.primary]
background = "#ffffff"
foreground = "#383a3f"

[colors.cursor]
text = "#ffffff"
cursor = "#6a6a6a"

[colors.selection]
text = "#383a3f"
background = "#e5deff"

[colors.normal]
black = "#ffffff"
red = "#fb7385"
green = "#98c379"
yellow = "#e5bc66"
blue = "#61afef"
magenta = "#ce95b8"
cyan = "#56b6c2"
white = "#383a3f"

[colors.bright]
black = "#8d8f9a"
red = "#fb7385"
green = "#98c379"
yellow = "#e5bc66"
blue = "#61afef"
magenta = "#ce95b8"
cyan = "#56b6c2"
white = "#383a3f"
