set $bg #2C2C3B
set $bg_alt #343445
set $fg #D0D0D9
set $muted #646078
set $accent #713A91
set $accent_border #814F9E
set $urgent #DD3962

client.focused          $muted $bg_alt $fg    $accent $muted
client.focused_inactive $bg    $bg_alt $muted $bg     $bg
client.unfocused        $bg    $bg     $muted $bg     $bg
client.urgent           $urgent $urgent        $fg    $urgent $fg
client.placeholder      $bg     $bg            $muted $bg     $bg

