set $bg #ffffff
set $bg_alt #f3f3f3
set $fg #383a3f
set $muted #8d8f9a
set $accent #fb7385
set $accent_border #98c379
set $urgent #ff4e4e

client.focused          $muted $bg_alt $fg    $accent $muted
client.focused_inactive $bg    $bg_alt $muted $bg     $bg
client.unfocused        $bg    $bg     $muted $bg     $bg
client.urgent           $urgent $urgent        $fg    $urgent $fg
client.placeholder      $bg     $bg            $muted $bg     $bg
