set $bg #20202a
set $bg_alt #22222e
set $fg #abb2bf
set $muted #495162
set $accent #fb7385
set $accent_border #98c379
set $urgent #ff4e4e

client.focused          $muted $bg_alt $fg    $accent $muted
client.focused_inactive $bg    $bg_alt $muted $bg     $bg
client.unfocused        $bg    $bg     $muted $bg     $bg
client.urgent           $urgent $urgent        $fg    $urgent $fg
client.placeholder      $bg     $bg            $muted $bg     $bg
