set $bg #F5F6FA
set $bg_alt #E7E9F2
set $fg #20202A
set $muted #9B97AD
set $accent #7A4DA3
set $accent_border #8A62B3
set $urgent #C72C52

client.focused          $muted $bg_alt $fg    $accent $muted
client.focused_inactive $bg    $bg_alt $muted $bg     $bg
client.unfocused        $bg    $bg     $muted $bg     $bg
client.urgent           $urgent $urgent        $fg    $urgent $fg
client.placeholder      $bg     $bg            $muted $bg     $bg

